# Generated by Django 6.0.1 on 2026-01-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('profile_image', models.ImageField(blank=True, default='example.png', upload_to='media')),
                ('profile_text', models.TextField()),
                ('btn1', models.CharField(max_length=50)),
                ('btn1_Link', models.TextField()),
                ('btn2', models.CharField(max_length=255)),
                ('btn2_Link', models.TextField()),
                ('point1', models.CharField(max_length=50)),
                ('point1_text', models.CharField(max_length=100)),
                ('point2', models.CharField(max_length=50)),
                ('point2_text', models.CharField(max_length=100)),
                ('point3', models.CharField(max_length=50)),
                ('point3_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='example.png', upload_to='media')),
                ('sideTitle', models.CharField(max_length=255)),
                ('mainTitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
    ]
