# Generated by Django 6.0.1 on 2026-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aboutsection_banner_delete_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('range_text', models.CharField(max_length=100)),
                ('range_percentage', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='point1',
            new_name='point1_number',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='point2',
            new_name='point2_number',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='point3',
            new_name='point3_number',
        ),
    ]
