# Generated by Django 6.0.1 on 2026-01-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skillsection_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSection',
            new_name='AboutSection_2',
        ),
        migrations.RenameModel(
            old_name='Banner',
            new_name='Banner_1',
        ),
        migrations.RenameModel(
            old_name='SkillSection',
            new_name='SkillSection_3',
        ),
    ]
