# Generated by Django 6.0.1 on 2026-01-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_aboutsection_aboutsection_2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSection_2',
            new_name='AboutSection',
        ),
        migrations.RenameModel(
            old_name='Banner_1',
            new_name='Banner',
        ),
        migrations.RenameModel(
            old_name='SkillSection_3',
            new_name='SkillSection',
        ),
    ]
