# Generated by Django 6.0.1 on 2026-01-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_aboutsection_2_aboutsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('service_icon', models.CharField(max_length=255)),
                ('service_name', models.CharField(max_length=255)),
                ('service_description', models.TextField()),
            ],
        ),
    ]
