# Generated by Django 6.0.1 on 2026-01-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_servicesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('filter_keyword', models.CharField(max_length=100)),
                ('project_url', models.CharField(max_length=255)),
                ('project_image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
