# Generated by Django 6.0.1 on 2026-01-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contactnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactnumber',
            name='email',
        ),
    ]
