# Generated by Django 6.0.1 on 2026-01-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_footertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footertext',
            name='footer_texts',
            field=models.TextField(),
        ),
    ]
