# Generated by Django 6.0.1 on 2026-01-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_footertext_footer_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='skillsection',
            name='title',
        ),
    ]
