# Generated by Django 6.0.1 on 2026-01-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_portfoliotitle_remove_portfoliosection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='greeting',
            field=models.CharField(default='Hello', max_length=255),
        ),
    ]
