# Generated by Django 6.0.1 on 2026-01-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_aboutsection_greeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientsection',
            name='title',
        ),
    ]
