# Generated by Django 6.0.1 on 2026-01-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_contacttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttitle',
            name='msg',
            field=models.CharField(default='Hey, Contact me', max_length=255),
        ),
    ]
