# Generated by Django 6.0.1 on 2026-01-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_contacttitle_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttitle',
            name='contact_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
