# Generated by Django 6.0.1 on 2026-01-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_contacttitle_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
