# Generated by Django 6.0.1 on 2026-01-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_banner_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='order',
        ),
    ]
