# Generated by Django 6.0.1 on 2026-01-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_banner_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='example.png', upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='SelfTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
