# Generated by Django 6.0.1 on 2026-01-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_bannerimage_selftag_delete_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(blank=True, default='profile.png', upload_to='media'),
        ),
    ]
