# Generated by Django 6.0.1 on 2026-01-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_bannerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='media'),
        ),
    ]
