# Generated by Django 6.0.1 on 2026-01-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_bannerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='contacttitle',
            name='contact_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='media'),
        ),
    ]
