# Generated by Django 6.0.1 on 2026-02-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_aboutsection_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_tag', models.CharField(max_length=100)),
                ('client_comments', models.TextField()),
                ('client_image', models.ImageField(default='media/default.png', upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='portfoliosection',
            name='project_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='media'),
        ),
    ]
