# Generated by Django 6.0.1 on 2026-02-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_testimonial_alter_portfoliosection_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsection',
            name='client_photo',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='media'),
        ),
    ]
