# Generated by Django 6.0.1 on 2026-02-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_clientsection_client_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
