# Generated by Django 6.0.1 on 2026-02-03 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_delete_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsection',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 3, 13, 6, 43, 777950)),
        ),
    ]
