# Generated by Django 6.0.1 on 2026-02-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_clientsection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsection',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
