# Generated by Django 6.0.1 on 2026-02-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_clientsection_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsection',
            options={'ordering': ['-date']},
        ),
    ]
