# Generated by Django 6.0.1 on 2026-02-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_clientsection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsection',
            options={},
        ),
        migrations.RemoveField(
            model_name='clientsection',
            name='date',
        ),
    ]
