# Generated by Django 6.0.1 on 2026-02-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_clientsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/profile_pic.png', upload_to='media'),
        ),
    ]
