# Generated by Django 6.0.1 on 2026-02-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_aboutsection_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='btn1_Link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='btn2_Link',
            field=models.URLField(),
        ),
    ]
