# Generated by Django 6.0.1 on 2026-02-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_aboutsection_btn1_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='media'),
        ),
    ]
